export const terms_condition =
  "<p><strong>Welcome to Our Hotel</strong></p><p>By proceeding with this self-service kiosk booking, you (Guest) agree to the following terms and conditions governing your stay at our hotel (Hotel). Please read these terms carefully before confirming your reservation.</p><p><strong>Check-In Requirements</strong></p><ul><li>All guests must be at least <strong>18 years of age</strong> to check in and register for a room.</li><li>A <strong>valid government-issued photo ID</strong> and a <strong>credit card</strong> are required at check-in.</li><li>The <strong>credit card used for booking must be presented</strong> by the cardholder.</li></ul><p><strong>Room Assignments &amp; Reservations</strong></p><ul><li>Room assignments are <strong>based on availability</strong> and cannot be guaranteed for specific room types or locations.</li><li><strong>Cancellations</strong> must be made at least <strong>24 hours prior</strong> to the scheduled arrival time to avoid penalties.</li><li><strong>Late cancellations or no-shows</strong> will result in a charge equal to <strong>one night's stay plus applicable taxes</strong>.</li><li><strong>Modifications</strong> to existing reservations are subject to availability and may result in rate changes.</li></ul><p><strong>Hotel Policies</strong></p><ul><li><strong>Maximum room occupancy limits</strong> must be strictly observed for safety and security reasons.</li><li><strong>Quiet hours</strong> are from <strong>10:00 PM to 7:00 AM</strong>.</li><li><strong>Smoking is prohibited</strong> in all indoor areas. A <strong>$250 cleaning fee</strong> will be charged for violations.</li><li><strong>Pets are not permitted</strong> unless specifically booked in a pet-friendly room with applicable fees paid.</li></ul><p><strong>Guest Responsibilities</strong></p><ul><li>The Hotel is <strong>not responsible for loss, theft, or damage</strong> to guest belongings.</li><li>Guests will be <strong>held financially responsible for any damage</strong> to Hotel property during their stay.</li><li>The Hotel reserves the right to <strong>charge the guest’s credit card</strong> for any damages discovered after check-out.</li></ul><p><strong>Privacy &amp; Security</strong></p><ul><li><strong>Personal information</strong> collected during booking will be processed in accordance with applicable <strong>privacy laws</strong>.</li><li><strong>Security cameras</strong> are in use in public areas for guest safety.</li><li>Guest information will <strong>not be shared</strong> with third parties except as required by law.</li></ul><p>By proceeding, you confirm that you have read and agree to these terms and conditions.</p>";

export const currency = "$";
export const currencyName = "USD";

export const dummay_QueAns = [
  {
    id: "5705321e-c64a-45ee-b62f-6500257ffa65",
    hotel_id: "ac9ece4f-38bc-4e76-bd37-70bf1eba181a",
    question_text: "Is this your first time visit?",
    question_type: "multiple_choice",
    is_mandatory: false,
    validation_rules: {},
    view_order: 1,
    is_active: true,
    created_at: "2025-04-25T10:29:37.381049+00:00",
    updated_at: "2025-05-08T06:49:18.472930+00:00",
    created_by: "pratapb.b@macrotech.net",
    updated_by: "pratapb.b@macrotech.net",
    kiosk_question_options: [
      {
        question_option_id: "d6968536-9031-4390-ba87-75c5f95e0228",
        option_text: "Yes",
        view_order: 1,
        created_at: "2025-04-25T10:29:37.465454+00:00",
        created_by: "pratapb.b@macrotech.net",
        updated_at: "2025-05-08T06:49:18.552945+00:00",
        updated_by: "pratapb.b@macrotech.net",
        question_action: null,
      },
      {
        question_option_id: "a9c89fb3-edbe-4694-aaa6-dac807f11d9c",
        option_text: "no",
        view_order: 2,
        created_at: "2025-04-26T03:38:50.154633+00:00",
        created_by: "pratap.b@macrotech.net",
        updated_at: "2025-05-08T06:49:18.631235+00:00",
        updated_by: "pratapb.b@macrotech.net",
        question_action: null,
      },
    ],
  },
  {
    id: "f4223ab5-48b2-4dc0-b889-a08c66e9a9c7",
    hotel_id: "ac9ece4f-38bc-4e76-bd37-70bf1eba181a",
    question_text: "Will you need parking?",
    question_type: "multiple_choice",
    is_mandatory: true,
    validation_rules: {},
    view_order: 2,
    is_active: true,
    created_at: "2025-04-25T10:29:37.381049+00:00",
    updated_at: "2025-04-28T05:52:50.184569+00:00",
    created_by: "pratapb.b@macrotech.net",
    updated_by: "pratapb.b@macrotech.net",
    kiosk_question_options: [
      {
        question_option_id: "0872cbb3-5bde-4d17-9d7c-443f1eb49f98",
        option_text: "Yes",
        view_order: 1,
        created_at: "2025-04-25T10:29:37.465454+00:00",
        created_by: "pratapb.b@macrotech.net",
        updated_at: "2025-04-28T05:52:50.25686+00:00",
        updated_by: "pratapb.b@macrotech.net",
        question_action: {
          question_action_id: "8aef8b8a-ac2d-439e-afa7-e767576aacca",
          code_name: "vehicle_no",
          action_name: "Vehicle No",
          is_active: true,
          created_at: "2025-04-25T07:23:30.253962+00:00",
          created_by: "pratap.b@macrotech.net",
          updated_at: null,
          updated_by: null,
        },
      },
      {
        question_option_id: "8164cc63-a177-48ff-aafc-ad4c81104206",
        option_text: "No",
        view_order: 2,
        created_at: "2025-04-28T05:52:50.48549+00:00",
        created_by: "pratapb.b@macrotech.net",
        updated_at: null,
        updated_by: null,
        question_action: null,
      },
    ],
  },
];

export const DummayAddon = [
  {
    id: "1d318b25-6899-4eb0-bc8f-18362e7e6807",
    hotel_id: "ac9ece4f-38bc-4e76-bd37-70bf1eba181a",
    code_name: "pet_charge",
    add_on_name: "Pet Charge",
    description: "Charge while Pet service in hotel by guest.",
    is_mandatory: false,
    applicant_type: "booking",
    amount_value_type: "flat_amount",
    is_taxable: false,
    tax_configuration_id: null,
    amount: 12,
    tax: 4,
    total_amount: 16,
    collection_timing: "at_check_in",
    frequency_type: "one_time",
    icon: "fa-solid fa-paw",
    is_active: true,
    created_at: "2025-02-25T07:51:49.231507+00:00",
    created_by: "system@macrotech.net",
    updated_at: "2025-02-28T09:53:21.515789+00:00",
    updated_by: "pratapb.b@macrotech.net",
  },
  {
    id: "88786055-1d0d-4dac-a1ed-786936d4b279",
    hotel_id: "ac9ece4f-38bc-4e76-bd37-70bf1eba181a",
    code_name: "late_check_out",
    add_on_name: "Late Checkout",
    description: "Charge while late check out by guest.",
    is_mandatory: false,
    applicant_type: "booking",
    amount_value_type: "flat_amount",
    is_taxable: false,
    tax_configuration_id: null,
    amount: 10,
    tax: 5,
    total_amount: 15,
    collection_timing: "at_check_out",
    frequency_type: "one_time",
    icon: "fa-solid fa-clock",
    is_active: true,
    created_at: "2025-02-25T07:51:49.231507+00:00",
    created_by: "system@macrotech.net",
    updated_at: "2025-02-28T09:52:45.447993+00:00",
    updated_by: "pratapb.b@macrotech.net",
  },
  {
    id: "55069ef5-6b78-48b1-aca9-cf79b19ade37",
    hotel_id: "ac9ece4f-38bc-4e76-bd37-70bf1eba181a",
    code_name: "accessible_room",
    add_on_name: "Accessible Room",
    description: "Charge while select Accessible room by guest.",
    is_mandatory: false,
    applicant_type: "booking",
    amount_value_type: "flat_amount",
    is_taxable: false,
    tax_configuration_id: null,
    amount: 15,
    tax: 2,
    total_amount: 17,
    collection_timing: "at_check_in",
    frequency_type: "one_time",
    icon: "fa-brands fa-accessible-icon",
    is_active: true,
    created_at: "2025-02-25T07:51:49.231507+00:00",
    created_by: "system@macrotech.net",
    updated_at: "2025-03-04T09:51:05.947700+00:00",
    updated_by: "pratapb.b@macrotech.net",
  },
  {
    id: "35c0249c-9400-4b7c-b06b-76960bc52a51",
    hotel_id: "ac9ece4f-38bc-4e76-bd37-70bf1eba181a",
    code_name: "smoking_room",
    add_on_name: "Smoking Room",
    description: "Charge while select Smoking room by guest.",
    is_mandatory: false,
    applicant_type: "booking",
    amount_value_type: "flat_amount",
    is_taxable: false,
    tax_configuration_id: "df5665fe-d4ad-4e03-b20c-f7255eb1d039",
    amount: 23,
    tax: 4,
    total_amount: 27,
    collection_timing: "at_check_in",
    frequency_type: "one_time",
    icon: "fa-solid fa-smoking",
    is_active: true,
    created_at: "2025-02-25T07:51:49.231507+00:00",
    created_by: "system@macrotech.net",
    updated_at: "2025-02-28T09:24:21.741728+00:00",
    updated_by: "pratapb.b@macrotech.net",
  },
];