// Helper function to get country code from country name
export const getCountryCodeFromName = (countryName) => {
  if (!countryName) return "us";

  const countryMapping = {
    // North America
    "united states": "us",
    usa: "us",
    america: "us",
    canada: "ca",

    // Europe
    "united kingdom": "gb",
    uk: "gb",
    england: "gb",
    britain: "gb",
    germany: "de",
    france: "fr",
    italy: "it",
    spain: "es",
    netherlands: "nl",
    belgium: "be",
    austria: "at",
    switzerland: "ch",
    portugal: "pt",
    poland: "pl",
    "czech republic": "cz",
    hungary: "hu",
    romania: "ro",
    bulgaria: "bg",
    croatia: "hr",
    slovenia: "si",
    slovakia: "sk",
    lithuania: "lt",
    latvia: "lv",
    estonia: "ee",
    finland: "fi",
    sweden: "se",
    norway: "no",
    denmark: "dk",
    iceland: "is",
    ireland: "ie",
    greece: "gr",
    cyprus: "cy",
    malta: "mt",
    luxembourg: "lu",

    // Asia
    india: "in",
    china: "cn",
    japan: "jp",
    "south korea": "kr",
    korea: "kr",
    thailand: "th",
    vietnam: "vn",
    singapore: "sg",
    malaysia: "my",
    indonesia: "id",
    philippines: "ph",
    taiwan: "tw",
    "hong kong": "hk",
    macau: "mo",
    "sri lanka": "lk",
    bangladesh: "bd",
    pakistan: "pk",
    nepal: "np",
    bhutan: "bt",
    maldives: "mv",
    myanmar: "mm",
    burma: "mm",
    cambodia: "kh",
    laos: "la",
    brunei: "bn",
    mongolia: "mn",
    kazakhstan: "kz",
    uzbekistan: "uz",
    kyrgyzstan: "kg",
    tajikistan: "tj",
    turkmenistan: "tm",
    afghanistan: "af",

    // Middle East
    "united arab emirates": "ae",
    uae: "ae",
    "saudi arabia": "sa",
    qatar: "qa",
    kuwait: "kw",
    bahrain: "bh",
    oman: "om",
    yemen: "ye",
    iraq: "iq",
    iran: "ir",
    turkey: "tr",
    israel: "il",
    palestine: "ps",
    jordan: "jo",
    lebanon: "lb",
    syria: "sy",
    cyprus: "cy",

    // Africa
    "south africa": "za",
    egypt: "eg",
    morocco: "ma",
    tunisia: "tn",
    algeria: "dz",
    libya: "ly",
    sudan: "sd",
    ethiopia: "et",
    kenya: "ke",
    uganda: "ug",
    tanzania: "tz",
    rwanda: "rw",
    burundi: "bi",
    madagascar: "mg",
    mauritius: "mu",
    seychelles: "sc",
    nigeria: "ng",
    ghana: "gh",
    "ivory coast": "ci",
    senegal: "sn",
    mali: "ml",
    "burkina faso": "bf",
    niger: "ne",
    chad: "td",
    cameroon: "cm",
    "central african republic": "cf",
    "democratic republic of congo": "cd",
    congo: "cg",
    gabon: "ga",
    "equatorial guinea": "gq",
    "sao tome and principe": "st",
    "cape verde": "cv",
    "guinea bissau": "gw",
    guinea: "gn",
    "sierra leone": "sl",
    liberia: "lr",
    togo: "tg",
    benin: "bj",
    namibia: "na",
    botswana: "bw",
    zimbabwe: "zw",
    zambia: "zm",
    malawi: "mw",
    mozambique: "mz",
    angola: "ao",
    lesotho: "ls",
    swaziland: "sz",
    eswatini: "sz",

    // Oceania
    australia: "au",
    "new zealand": "nz",
    fiji: "fj",
    "papua new guinea": "pg",
    "solomon islands": "sb",
    vanuatu: "vu",
    "new caledonia": "nc",
    "french polynesia": "pf",
    samoa: "ws",
    tonga: "to",
    kiribati: "ki",
    tuvalu: "tv",
    nauru: "nr",
    palau: "pw",
    "marshall islands": "mh",
    micronesia: "fm",

    // South America
    brazil: "br",
    argentina: "ar",
    chile: "cl",
    peru: "pe",
    colombia: "co",
    venezuela: "ve",
    ecuador: "ec",
    bolivia: "bo",
    paraguay: "py",
    uruguay: "uy",
    guyana: "gy",
    suriname: "sr",
    "french guiana": "gf",

    // 
    // Central America & Caribbean
    mexico: "mx",
    guatemala: "gt",
    belize: "bz",
    "el salvador": "sv",
    honduras: "hn",
    nicaragua: "ni",
    "costa rica": "cr",
    panama: "pa",
    cuba: "cu",
    jamaica: "jm",
    haiti: "ht",
    "dominican republic": "do",
    "puerto rico": "pr",
    "trinidad and tobago": "tt",
    barbados: "bb",
    bahamas: "bs",
    "antigua and barbuda": "ag",
    "saint kitts and nevis": "kn",
    dominica: "dm",
    "saint lucia": "lc",
    "saint vincent and the grenadines": "vc",
    grenada: "gd",
  };

  const normalizedCountry = countryName.toLowerCase().trim();
  return countryMapping[normalizedCountry] || "us";
};
